name: Sample-workflow

on:
  workflow_dispatch:
    input:
        envinronment:
          required: true
          default: "eastus"
          type: choice
          options:
            - westus
            - centalus

job:
 run:
  runs-on: ubantu-latest
  steps:
    -name: Checkout module repo
     uses: actions/checkout@v4

    - name: Run task
      run: each " Run task"
    
